=== meikyour/LM/Tema04/17-Docencia/docencia.dtd
<!ELEMENT docencia (modulos, profesores)>
<!ELEMENT modulos (modulo+)>
<!ELEMENT modulo (#PCDATA)>
<!ATTLIST modulo
          id ID #REQUIRED>
<!ELEMENT profesores (profesor+)>
<!ELEMENT profesor (#PCDATA)>
<!ATTLIST profesor
          modulo IDREF #REQUIRED>

=== meikyour/LM/Tema04/17-Docencia/docencia.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE docencia SYSTEM "docencia.dtd">
<docencia>
  <modulos>
    <modulo id="a1">Programacion</modulo>
    <modulo id="a2">Bases de datos</modulo>
    <modulo id="a3">Lenguaje de marcas</modulo>
    <modulo id="a4">Entornos de desarrollo</modulo>
    <modulo id="a5">Ingles</modulo>
    <modulo id="a6">Sistemas</modulo>
  </modulos>
  <profesores>
    <profesor modulo="a1">Jose Antonio Pacheco</profesor>
    <profesor modulo="a6">Miguel Villar</profesor>
    <profesor modulo="a2">Francisco Blasco</profesor>
    <profesor modulo="a5">Merce Dantes</profesor>
  </profesores>
</docencia>
