=== meikyour/LM/Tema04/dtd_mega/eje21/hemeroteca.dtd
<!ELEMENT hemeroteca (socios,periodicos,revistas,peticiones)>
<!ELEMENT socios (socio+)>
<!ELEMENT socio EMPTY>
<!ATTLIST socio
      id_socio ID #REQUIRED>
<!ELEMENT periodicos (periodico+)>
<!ELEMENT periodico EMPTY>
<!ATTLIST periodico
      id_periodico ID #REQUIRED
      nombre CDATA #REQUIRED
      fecha_publicacion CDATA #REQUIRED>
<!ELEMENT revistas (revista+)>
<!ELEMENT revista EMPTY>
<!ATTLIST revista
      id_revista ID #REQUIRED
      nombre CDATA #REQUIRED
      numero CDATA #REQUIRED>
<!ELEMENT peticiones (peticion+)>
<!ELEMENT peticion EMPTY>
<!ATTLIST peticion
      id_socio IDREF #REQUIRED
      id_revista IDREF #IMPLIED 
      id_periodico IDREF #IMPLIED
      fecha_peticion CDATA #REQUIRED
      dias_prestamo CDATA #REQUIRED>

=== meikyour/LM/Tema04/dtd_mega/eje21/hemeroteca.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE hemeroteca SYSTEM "hemeroteca.dtd">
<hemeroteca>

<socios>
<socio id_socio="s001"/>
</socios>

<periodicos>
<periodico id_periodico="p001" nombre="El Pais" fecha_publicacion="1/1/1970"/>
</periodicos>

<revistas>
<revista id_revista="r001" nombre="Saber vivir" numero="208"/>
</revistas>

<peticiones>
<peticion id_socio="s001" id_revista="r001" fecha_peticion="10/11/16" dias_prestamo="10"/>
<peticion id_socio="s001" id_periodico="p001" fecha_peticion="10/11/16" dias_prestamo="10"/>
</peticiones>

</hemeroteca>
