=== meikyour/LM/Tema04/Colecta/colecta.dtd
<!ELEMENT colecta (donativos, personas)>
<!ATTLIST colecta
          objetivo CDATA #REQUIRED>
<!ELEMENT donativos (donativo+)>
<!ELEMENT donativo (#PCDATA)>
<!ATTLIST donativo
          persona IDREF #REQUIRED>
<!ELEMENT personas (persona+)>
<!ELEMENT persona (nombre, apellido, apellido?)>
<!ATTLIST persona
          id ID #REQUIRED>
<!ELEMENT nombre   (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>

=== meikyour/LM/Tema04/Colecta/colecta.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE colecta SYSTEM "colecta.dtd">
<colecta objetivo="El cambio climático">
  <donativos>
    <donativo persona="p01">6</donativo>
    <donativo persona="p02">4</donativo>
    <donativo persona="p03">10</donativo>
  </donativos>
  <personas>
    <persona id="p01">
      <nombre>Pepe</nombre>
      <apellido>García</apellido>
    </persona>
    <persona id="p02">
      <nombre>Pepe</nombre>
      <apellido>García</apellido>
      <apellido>Mano</apellido>
    </persona>
    <persona id="p03">
      <nombre>Yolanda</nombre>
      <apellido>Ramos</apellido>
      <apellido>Calvo</apellido>
    </persona>
  </personas>
</colecta>
