=== meikyour/LM/Tema04/21-Hemeroteca/hemeroteca.dtd
<!ELEMENT hemeroteca (peticiones, fecha, socios, generos)>
<!ELEMENT peticiones (peticion+)>
<!ELEMENT peticion (num_socio, num_recogida, num_devolucion)>
<!ATTLIST peticion
          articulo IDREF #REQUIRED>
<!ELEMENT num_socio (#PCDATA)>
<!ELEMENT num_recogida (#PCDATA)>
<!ELEMENT num_devolucion (#PCDATA)>
<!ELEMENT fecha (recogidas, devoluciones)>
<!ELEMENT recogidas (recogida+)>
<!ELEMENT recogida (#PCDATA)>
<!ATTLIST recogida
          id ID #REQUIRED>
<!ELEMENT devoluciones (devolucion+)>
<!ELEMENT devolucion (#PCDATA)>
<!ATTLIST devolucion
          id ID #REQUIRED>
<!ELEMENT socios (socio+)>
<!ELEMENT socio (#PCDATA)>
<!ATTLIST socio
          id ID #REQUIRED>
<!ELEMENT generos (genero+)>
<!ELEMENT genero (nombre, publicacion)>
<!ATTLIST genero
          id ID #REQUIRED
          tipo CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT publicacion (#PCDATA)>

=== meikyour/LM/Tema04/21-Hemeroteca/hemeroteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hemeroteca SYSTEM "hemeroteca.dtd">
<hemeroteca>
  <peticiones>
    <peticion articulo="p1">
      <num_socio>s1</num_socio>
      <num_recogida>re2</num_recogida> 
      <num_devolucion>d2</num_devolucion>
    </peticion>
    <peticion articulo="r2">
      <num_socio>s1</num_socio>
      <num_recogida>re2</num_recogida> 
      <num_devolucion>d2</num_devolucion>
    </peticion>
    <peticion articulo="r1">
      <num_socio>s2</num_socio>
      <num_recogida>re2</num_recogida> 
      <num_devolucion>d2</num_devolucion>
    </peticion>
  </peticiones>
  <fecha>
    <recogidas>
      <recogida id="re1">06/10/2016</recogida>
      <recogida id="re2">08/09/2016</recogida>
      <recogida id="re3">04/02/2012</recogida>
      <recogida id="re4">03/08/2015</recogida>
    </recogidas>
    <devoluciones>
      <devolucion id="d1">08/10/2016</devolucion>
      <devolucion id="d2">10/09/2016</devolucion>
      <devolucion id="d3">05/02/2012</devolucion>
      <devolucion id="d4">08/08/2015</devolucion>
    </devoluciones>
  </fecha>
  <socios>
    <socio id="s1">Raul Suarez</socio>
    <socio id="s2">Nestor Agrasot</socio>
    <socio id="s3">Pepito Grillo</socio>
  </socios>
  <generos>
    <genero tipo="Periodico" id="p1">
      <nombre>Las Provincias</nombre>
      <publicacion>22/10/2016</publicacion>
    </genero>
    <genero tipo="Periodico" id="p2">
      <nombre>Levante</nombre>
      <publicacion>24/09/2016</publicacion>
    </genero>
    <genero tipo="Revista" id="r1">
      <nombre>Personal Computer</nombre>
      <publicacion>22/10/1999</publicacion>
    </genero>
    <genero tipo="Revista" id="r2">
      <nombre>Family PC</nombre>
      <publicacion>22/10/1994</publicacion>
    </genero>
  </generos>
</hemeroteca>
