=== meikyour/LM/Tema04/dtd_mega/eje18/alumno_modulo.dtd
<!ELEMENT centro (alumnos,clase)>
<!ELEMENT alumnos (alumno+)>
<!ELEMENT alumno (modulo+)>
<!ATTLIST alumno
alumno_id ID  #REQUIRED
id_clase IDREF #REQUIRED
nombre CDATA #REQUIRED>
<!ELEMENT modulo EMPTY>
<!ATTLIST modulo
id_modulo IDREF #REQUIRED>

<!ELEMENT clase (modulo_clase+)>
<!ATTLIST clase
id_clase ID #REQUIRED>
<!ELEMENT modulo_clase EMPTY>
<!ATTLIST modulo_clase
id_modulo ID #REQUIRED
nombre_modulo CDATA #REQUIRED>

=== meikyour/LM/Tema04/dtd_mega/eje18/alumno_modulo.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE centro SYSTEM "alumno_modulo.dtd">
<centro>
<alumnos>
<alumno alumno_id="a001" id_clase="c001" nombre="Angel">
<modulo id_modulo="m101"/>
<modulo id_modulo="m102"/>
</alumno>
</alumnos>
<clase id_clase="c001">
<modulo_clase id_modulo="m101" nombre_modulo="BD"/>
<modulo_clase id_modulo="m102" nombre_modulo="ED"/>
</clase>
</centro>
