=== meikyour/LM/Tema04/dtd_mega/eje22/transferencias.dtd
<!ELEMENT banco (clientes,transferencias)>
<!ELEMENT clientes (cliente+)>
<!ELEMENT cliente EMPTY>
<!ATTLIST cliente
      id_cuenta ID #REQUIRED
      dni CDATA #REQUIRED
      nombre CDATA #REQUIRED
      primer_apellido CDATA #REQUIRED
      segundo_apellido CDATA #IMPLIED>
<!ELEMENT transferencias (transferencia+)>
<!ELEMENT transferencia (origen,destino,comentario)>
<!ATTLIST transferencia
 fecha CDATA #REQUIRED
moneda CDATA #REQUIRED
cantidad CDATA #REQUIRED
tipo CDATA #REQUIRED
hora CDATA #REQUIRED>
<!ELEMENT origen EMPTY>
<!ATTLIST origen
id_cuenta IDREF #REQUIRED>
<!ELEMENT destino EMPTY>
<!ATTLIST destino
id_cuenta IDREF #REQUIRED>
<!ELEMENT comentario (#PCDATA)>

=== meikyour/LM/Tema04/dtd_mega/eje22/transferencias.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE banco SYSTEM "transferencias.dtd">
<banco>
<clientes>
<cliente id_cuenta="A00010001019874215360" dni="134A" nombre="Angel" primer_apellido="Pastelero" segundo_apellido=""/>
<cliente id_cuenta="A00010001015440747847" dni="134A" nombre="Angel" primer_apellido="Pastelero" segundo_apellido=""/>
</clientes>

<transferencias>
<transferencia fecha="1/1/99" moneda="" cantidad="" tipo="normal" hora="12:20">
<origen id_cuenta="A00010001019874215360"/>
<destino id_cuenta="A00010001015440747847"/>
<comentario>Hola</comentario>
</transferencia>
</transferencias>
</banco>
