=== meikyour/LM/Tema04/18-Alumno_Modulo/alumno_modulo.dtd
<!ELEMENT alumno_modulo (modulos, alumnos)>
<!ELEMENT modulos (modulo+)>
<!ELEMENT modulo (#PCDATA)>
<!ATTLIST modulo
          id ID #REQUIRED>
<!ELEMENT alumnos (alumno+)>
<!ELEMENT alumno (#PCDATA)>
<!ATTLIST alumno
          modulo IDREF #REQUIRED>

=== meikyour/LM/Tema04/18-Alumno_Modulo/alumno_modulo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alumno_modulo SYSTEM "alumno_modulo.dtd">
<alumno_modulo>
  <modulos>
    <modulo id="a1">Programacion</modulo>
    <modulo id="a2">Bases de datos</modulo>
    <modulo id="a3">Lenguaje de marcas</modulo>
    <modulo id="a4">Entornos de desarrollo</modulo>
    <modulo id="a5">Ingles</modulo>
    <modulo id="a6">Sistemas</modulo>
  </modulos>
  <alumnos>
    <alumno modulo="a1">Francisco Engix</alumno>
    <alumno modulo="a6">Raul Granel</alumno>
    <alumno modulo="a2">Yolanda Gaona</alumno>
    <alumno modulo="a5">Elisa Oliver</alumno>
  </alumnos>
</alumno_modulo>
