=== meikyour/LM/Tema04/19-Altas/altas.dtd
<!ELEMENT altas (fechas, personas)>
<!ELEMENT fechas (fecha+)>
<!ELEMENT fecha (#PCDATA)>
<!ATTLIST fecha
          persona IDREF #REQUIRED>
<!ELEMENT personas (persona+)>
<!ELEMENT persona (nombre, apellido, apellido?)>
<!ATTLIST persona
          id ID #REQUIRED>
<!ELEMENT nombre   (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>

=== meikyour/LM/Tema04/19-Altas/altas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE altas SYSTEM "altas.dtd">
<altas>
  <fechas>
    <fecha persona="p01">6</fecha>
    <fecha persona="p02">4</fecha>
    <fecha persona="p03">10</fecha>
  </fechas>
  <personas>
    <persona id="p01">
      <nombre>Jose</nombre>
      <apellido>Masmano</apellido>
    </persona>
    <persona id="p02">
      <nombre>Luz</nombre>
      <apellido>García</apellido>
      <apellido>Cruz</apellido>
    </persona>
    <persona id="p03">
      <nombre>Elisa</nombre>
      <apellido>Ramos</apellido>
      <apellido>Lopez</apellido>
    </persona>
  </personas>
</altas>
